// ═══════════════════════════════════════════
//  DerivX Book Data
//  All chapter content, problems, formulas
// ═══════════════════════════════════════════

export const BOOK_META = {
  title: 'Options, Futures, and Other Derivatives',
  author: 'John C. Hull',
  edition: '11th Edition',
  totalChapters: 37,
}

// ── Chapter Registry ──
export const CHAPTERS = [
  { id: 'ch1', num: 1, title: 'Introduction', status: 'available',
    topics: 'Derivatives, Forwards, Futures, Options, Traders',
    desc: 'The building blocks — what derivatives are, who uses them and why.' },
  { id: 'ch2', num: 2, title: 'Futures Markets & Central Counterparties', status: 'available',
    topics: 'Margin accounts, convergence, OTC clearing, delivery',
    desc: 'How futures exchanges work, margin mechanics, and the CCP revolution.' },
  { id: 'ch3', num: 3, title: 'Hedging Strategies Using Futures', status: 'coming',
    topics: 'Basis risk, cross hedging, stock index futures', desc: '' },
  { id: 'ch4', num: 4, title: 'Interest Rates', status: 'coming',
    topics: 'Zero rates, bond pricing, duration, convexity', desc: '' },
  { id: 'ch5', num: 5, title: 'Forward & Futures Prices', status: 'coming',
    topics: 'Cost of carry, investment vs consumption assets', desc: '' },
  { id: 'ch6', num: 6, title: 'Interest Rate Futures', status: 'coming',
    topics: 'Treasury bond futures, SOFR, duration hedging', desc: '' },
  { id: 'ch7', num: 7, title: 'Swaps', status: 'coming',
    topics: 'IRS mechanics, comparative advantage, valuation', desc: '' },
  { id: 'ch8', num: 8, title: 'Securitization & 2008 Crisis', status: 'coming',
    topics: 'CDOs, MBS, what went wrong', desc: '' },
  { id: 'ch9', num: 9, title: 'XVAs', status: 'coming',
    topics: 'CVA, DVA, FVA, MVA, KVA', desc: '' },
  { id: 'ch10', num: 10, title: 'Options Markets', status: 'coming',
    topics: 'Calls, puts, positions, margin, OCC', desc: '' },
]

// ── Chapter 1 Full Data ──
export const CH1_DATA = {
  id: 'ch1',
  num: 1,
  title: 'Introduction',

  // ── FORMULAS ──
  formulas: [
    {
      id: 'fwd_payoff_long',
      category: 'Forward Contracts',
      name: 'Long Forward Payoff',
      formula: 'Payoff = S_T − K',
      latex: 'Payoff_{long} = S_T - K',
      variables: [
        { symbol: 'S_T', meaning: 'Spot price at maturity' },
        { symbol: 'K', meaning: 'Agreed forward price' },
      ],
      note: 'Positive when spot price at maturity exceeds the forward price agreed today.',
      example: 'K = ₹100, S_T = ₹120 → Payoff = ₹20',
    },
    {
      id: 'fwd_payoff_short',
      category: 'Forward Contracts',
      name: 'Short Forward Payoff',
      formula: 'Payoff = K − S_T',
      variables: [
        { symbol: 'K', meaning: 'Agreed forward price' },
        { symbol: 'S_T', meaning: 'Spot price at maturity' },
      ],
      note: 'Profitable when the spot price falls below the agreed forward price.',
      example: 'K = ₹100, S_T = ₹85 → Payoff = ₹15',
    },
    {
      id: 'call_payoff',
      category: 'Options',
      name: 'Call Option Payoff (Buyer)',
      formula: 'Payoff = max(S_T − K, 0)',
      variables: [
        { symbol: 'S_T', meaning: 'Stock price at expiry' },
        { symbol: 'K', meaning: 'Strike price' },
      ],
      note: 'The call buyer exercises only when S_T > K. Otherwise, the option expires worthless.',
      example: 'K = ₹100, S_T = ₹115 → Payoff = ₹15',
    },
    {
      id: 'put_payoff',
      category: 'Options',
      name: 'Put Option Payoff (Buyer)',
      formula: 'Payoff = max(K − S_T, 0)',
      variables: [
        { symbol: 'K', meaning: 'Strike price' },
        { symbol: 'S_T', meaning: 'Stock price at expiry' },
      ],
      note: 'The put buyer exercises only when K > S_T. Benefits from falling prices.',
      example: 'K = ₹100, S_T = ₹78 → Payoff = ₹22',
    },
    {
      id: 'call_profit',
      category: 'Options',
      name: 'Call Option Profit (Buyer)',
      formula: 'Profit = max(S_T − K, 0) − c',
      variables: [
        { symbol: 'c', meaning: 'Call premium paid' },
        { symbol: 'K', meaning: 'Strike price' },
        { symbol: 'S_T', meaning: 'Stock price at expiry' },
      ],
      note: 'Breakeven at S_T = K + c. Maximum loss is the premium paid.',
      example: 'K = ₹100, c = ₹10, S_T = ₹118 → Profit = ₹8',
    },
    {
      id: 'put_profit',
      category: 'Options',
      name: 'Put Option Profit (Buyer)',
      formula: 'Profit = max(K − S_T, 0) − p',
      variables: [
        { symbol: 'p', meaning: 'Put premium paid' },
        { symbol: 'K', meaning: 'Strike price' },
        { symbol: 'S_T', meaning: 'Stock price at expiry' },
      ],
      note: 'Breakeven at S_T = K − p. Max gain = K − p (if stock goes to zero).',
      example: 'K = ₹100, p = ₹8, S_T = ₹82 → Profit = ₹10',
    },
  ],

  // ── KEY SUMMARY ──
  summary: {
    tagline: 'The building blocks of the entire derivatives universe.',
    keyPoints: [
      {
        icon: '🔗',
        title: 'What Is a Derivative?',
        body: "A financial contract whose value is DERIVED from an underlying asset (stock, bond, commodity, currency, or interest rate). The underlying determines the derivative's value — not the other way around.",
      },
      {
        icon: '🏛️',
        title: 'Two Market Types',
        body: 'Exchange-traded: standardized, CCP-cleared, transparent, margin required. OTC: customized, bilateral, counterparty risk, more flexible. OTC is larger by notional value (>$600 trillion).',
      },
      {
        icon: '📅',
        title: 'Forward vs Futures',
        body: 'Both lock in a future price. Forwards: OTC, customized, settled at maturity, zero upfront cost. Futures: exchange-traded, standardized, marked to market daily. Most futures never physically deliver.',
      },
      {
        icon: '🎯',
        title: 'Options: The Asymmetric Instrument',
        body: "Options give the RIGHT but not OBLIGATION to buy (call) or sell (put) at strike K. Buyer pays a premium — their maximum loss. Seller receives premium — their maximum gain. The asymmetry is what makes options unique.",
      },
      {
        icon: '🛡️',
        title: 'Three Types of Traders',
        body: 'Hedgers: reduce existing risk (airlines buying fuel futures). Speculators: take on risk for profit using leverage. Arbitrageurs: exploit price discrepancies for risk-free profit. All three are essential to market efficiency.',
      },
      {
        icon: '⚠️',
        title: 'The Danger',
        body: "Derivatives amplify both gains AND losses. Barings Bank (1995): £830M loss from unauthorized futures. LTCM (1998): Nobel Prize winners' fund collapsed. Orange County (1994): $1.7B loss. Derivatives are tools, not toys.",
      },
    ],
    mustRemember: [
      'Derivative value = f(underlying asset price)',
      'Forward payoff (long) = S_T − K; (short) = K − S_T',
      'Option payoff (call) = max(S_T − K, 0)',
      'Option payoff (put) = max(K − S_T, 0)',
      'Max loss for option buyer = premium paid',
      'Exchange-traded → clearing house eliminates counterparty risk',
      'Hedgers reduce risk; speculators take risk; arbitrageurs remove risk-free profit',
    ],
    connections: [
      'Chapter 1 concepts underpin ALL of Hull — every later chapter builds on these basics',
      'Forward payoff formula reappears in Ch5 (pricing), Ch13 (BSM), and beyond',
      'Three trader types recur throughout the book in different contexts',
    ],
  },

  // ── TEXTBOOK EXAMPLES ──
  examples: [
    {
      id: 'ex1_1',
      num: '1.1',
      type: 'worked',
      title: 'Hull\'s Gold Forward Example',
      scenario: 'Exchange Rate Hedging',
      problem:
        "On January 3, a US company agrees to pay £1 million in 6 months for goods imported from the UK. The current exchange rate is $1.4800 per pound. The company enters a 6-month forward contract with a bank at $1.4900 per pound. What happens at maturity if the rate is (a) $1.6000 or (b) $1.3000?",
      solution: [
        'Contract locks in: £1,000,000 × $1.4900 = $1,490,000 payment',
        '',
        'Case (a): Spot = $1.6000/£',
        '  Without hedge: pay $1,600,000',
        '  With forward: pay $1,490,000',
        '  Saving: $110,000 ✅',
        '',
        'Case (b): Spot = $1.3000/£',
        '  Without hedge: pay $1,300,000',
        '  With forward: pay $1,490,000',
        '  "Cost": $190,000 (but budget certainty was the goal)',
        '',
        'Key insight: The hedger is not trying to profit — they are eliminating uncertainty.',
      ],
      insight:
        'This is the fundamental use case for forwards. The company does not know if the hedge will "make money" in hindsight — the point is budget certainty.',
      tags: ['Forward', 'Hedging', 'Currency'],
    },
    {
      id: 'ex1_2',
      num: '1.2',
      type: 'worked',
      title: 'Speculator Using Futures vs Spot',
      scenario: 'Leverage in Speculation',
      problem:
        'An investor has $5,800 and expects the British pound to rise vs USD. Current spot: $1.4700/£. A 3-month futures contract is available at $1.4700/£ for £62,500 per contract. Initial margin = $5,000.',
      solution: [
        'Strategy A — Buy spot:',
        '  Can buy: $5,800 / $1.4700 = £3,945',
        '',
        'Strategy B — Buy futures:',
        '  Put $5,000 as margin (keeps $800 in T-bills)',
        '  Controls: £62,500 worth of GBP',
        '',
        'If GBP rises to $1.5200 (+3.4%):',
        '  Spot gain: £3,945 × $0.05 = $197 (3.4% return)',
        '  Futures gain: £62,500 × $0.05 = $3,125 (53.9% return!)',
        '',
        'If GBP falls to $1.4200 (−3.4%):',
        '  Spot loss: $197 (3.4% loss)',
        '  Futures loss: $3,125 (53.9% loss!)',
        '',
        'Leverage = £62,500 / £3,945 ≈ 15.8× amplification',
      ],
      insight:
        'Futures provide massive leverage — the same capital controls 15.8× the exposure. This is why derivatives are powerful for speculators and dangerous for the unprepared.',
      tags: ['Futures', 'Speculation', 'Leverage'],
    },
    {
      id: 'ex1_3',
      num: '1.3',
      type: 'worked',
      title: "Arbitrageur: Microsoft Stock",
      scenario: 'Cross-Market Arbitrage',
      problem:
        "Microsoft trades at $172 on NYSE and £124 on LSE. Current exchange rate: $1.4400 per pound. Is there an arbitrage opportunity? (Ignore transaction costs.)",
      solution: [
        'Step 1: Convert LSE price to USD',
        '  £124 × $1.4400 = $178.56',
        '',
        'Step 2: Compare',
        '  NYSE: $172.00',
        '  LSE (in USD): $178.56',
        '',
        'Step 3: Execute arbitrage',
        '  Buy 1,000 shares on NYSE: −$172,000',
        '  Sell 1,000 shares on LSE: +$178,560',
        '  Risk-free profit: $6,560 instantaneously',
        '',
        'What happens next?',
        '  Buying on NYSE pushes NYSE price UP',
        '  Selling on LSE pushes LSE price DOWN',
        '  Exchange rate adjusts',
        '  Arbitrage disappears in seconds in efficient markets',
      ],
      insight:
        "Arbitrage opportunities like this are self-eliminating — the very act of exploiting them removes them. In modern markets, algorithms detect and eliminate arbitrage in milliseconds.",
      tags: ['Arbitrage', 'Efficiency', 'Cross-market'],
    },
    {
      id: 'ex1_4',
      num: '1.4',
      type: 'worked',
      title: 'Call Option Profit Calculation',
      scenario: 'Long Call Analysis',
      problem:
        "An investor pays $2.50 for a 3-month call option to buy Microsoft stock with a strike price of $29 (current price = $29). They have $5,800. Option covers 100 shares. Calculate P&L if stock goes to (a) $35 or (b) $23 at expiry.",
      solution: [
        'Cost of 100-share call contract: $2.50 × 100 = $250',
        '',
        'Case (a): Stock = $35',
        '  Exercise the call: buy at $29, sell at $35',
        '  Gross payoff: ($35 − $29) × 100 = $600',
        '  Net profit: $600 − $250 = $350',
        '  Return: 140% on $250 investment',
        '',
        'Case (b): Stock = $23',
        '  Option expires worthless (S < K)',
        '  Loss = entire premium: $250',
        '  Return: −100% on $250 investment',
        '',
        'Compare to buying 200 shares at $29 (same $5,800 budget):',
        '  Case (a): gain = 200 × $6 = $1,200 (+20.7%)',
        '  Case (b): loss = 200 × $6 = −$1,200 (−20.7%)',
        '',
        'Options offer higher % return potential but risk losing entire investment.',
      ],
      insight:
        'The option gives highly leveraged exposure with limited downside (only the premium). But this leverage cuts both ways — you can lose 100% of your investment.',
      tags: ['Call Option', 'Leverage', 'Profit/Loss'],
    },
  ],

  // ── TEXTBOOK PRACTICE PROBLEMS ──
  problems: [
    {
      id: 'p1_12',
      num: '1.12',
      difficulty: 'medium',
      type: 'numerical',
      topic: 'Short Forward',
      problem:
        "An investor enters into a short forward contract to sell 100,000 British pounds for U.S. dollars at an exchange rate of 1.3000 USD per pound. How much does the investor gain or lose if the exchange rate at the end of the contract is (a) 1.2900 and (b) 1.3200?",
      hints: [
        'Short forward payoff = K − S_T per unit',
        'Multiply by contract size (100,000 pounds)',
        'Positive payoff = gain; negative = loss',
      ],
      solution: {
        steps: [
          'Short forward: sell £100,000 at K = $1.3000/£',
          '',
          'Case (a): S_T = $1.2900/£',
          '  Payoff per pound = K − S_T = 1.3000 − 1.2900 = $0.0100',
          '  Total gain = 100,000 × $0.0100 = $1,000 ✅',
          '',
          'Case (b): S_T = $1.3200/£',
          '  Payoff per pound = K − S_T = 1.3000 − 1.3200 = −$0.0200',
          '  Total loss = 100,000 × $0.0200 = $2,000 ❌',
          '',
          'Short forward gains when spot falls below K, loses when spot rises above K.',
        ],
        final: 'Gain = $1,000 (a) | Loss = $2,000 (b)',
      },
    },
    {
      id: 'p1_13',
      num: '1.13',
      difficulty: 'medium',
      type: 'numerical',
      topic: 'Short Futures',
      problem:
        'A trader enters into a short cotton futures contract when the futures price is 50 cents per pound. The contract is for 50,000 pounds. How much does the trader gain or lose if the cotton price at end of the contract is (a) 48.20 cents and (b) 51.30 cents?',
      hints: [
        'Short futures: you agreed to SELL at 50 cents',
        'Gain = (entry price − exit price) × contract size',
        'Convert cents to dollars for final answer',
      ],
      solution: {
        steps: [
          'Entry (short): sell at 50 cents = $0.5000/lb',
          'Contract size: 50,000 pounds',
          '',
          'Case (a): Price = 48.20 cents = $0.4820/lb',
          '  Gain per lb = 0.5000 − 0.4820 = $0.0180',
          '  Total gain = 50,000 × $0.0180 = $900 ✅',
          '',
          'Case (b): Price = 51.30 cents = $0.5130/lb',
          '  Loss per lb = 0.5130 − 0.5000 = $0.0130',
          '  Total loss = 50,000 × $0.0130 = $650 ❌',
        ],
        final: 'Gain = $900 (a) | Loss = $650 (b)',
      },
    },
    {
      id: 'p1_14',
      num: '1.14',
      difficulty: 'hard',
      type: 'conceptual',
      topic: 'Short Put',
      problem:
        'Suppose you write a put contract with a strike price of $40 and expiration in 3 months. The current stock price is $41 and the contract is on 100 shares. What have you committed to? How much could you gain or lose?',
      hints: [
        'You are the SHORT (seller) of the put',
        'The put buyer has the right to SELL to you at $40',
        'You must buy at $40 if the buyer exercises',
      ],
      solution: {
        steps: [
          'You (short put) are OBLIGATED to buy 100 shares at $40 if exercised.',
          '',
          'The put buyer will exercise when S_T < $40.',
          '',
          'Maximum gain: the premium received (the buyer pays you upfront)',
          '  If S_T ≥ $40: option expires worthless, you keep premium',
          '',
          'Maximum loss: if S_T → $0',
          '  You buy 100 shares at $40 each = $4,000 outlay',
          '  Shares worth $0 → loss = $4,000 − premium received',
          '',
          'Profit at expiry = premium − max(K − S_T, 0) × 100',
          '',
          'Example: If premium = $3 and S_T = $30:',
          '  Loss = ($40 − $30 − $3) × 100 = $700',
        ],
        final: 'Max gain = premium received | Max loss = (K − premium) × 100 = up to $3,700',
      },
    },
    {
      id: 'p1_15',
      num: '1.15',
      difficulty: 'hard',
      type: 'comparative',
      topic: 'Stock vs Option Speculation',
      problem:
        "You expect a rise in a stock currently priced at $29. A 3-month call option with K = $30 costs $2.90. You have $5,800. Compare: (A) buy shares, (B) buy call options. What are the potential gains/losses?",
      hints: [
        'Strategy A: buy $5800/$29 = 200 shares',
        'Strategy B: buy $5800/$2.90 = 2,000 options (on 2,000 shares)',
        'Compare if stock goes to $35 vs $25',
      ],
      solution: {
        steps: [
          'Strategy A — Buy shares:',
          '  Buy 200 shares at $29 = $5,800 invested',
          '',
          '  If S_T = $35: gain = 200 × $6 = $1,200 (+20.7%)',
          '  If S_T = $25: loss = 200 × $4 = −$800 (−13.8%)',
          '',
          'Strategy B — Buy call options:',
          '  Buy $5,800 / $2.90 = 2,000 call options (K = $30)',
          '',
          '  If S_T = $35: payoff = 2,000 × (35−30) = $10,000',
          '    Profit = $10,000 − $5,800 = $4,200 (+72.4%)',
          '  If S_T = $25: options expire worthless',
          '    Loss = −$5,800 (−100%)',
          '',
          'Options offer MUCH higher upside BUT much worse downside.',
        ],
        final: 'At $35: Options +72.4% vs Shares +20.7% | At $25: Options −100% vs Shares −13.8%',
      },
    },
    {
      id: 'p1_25',
      num: '1.25',
      difficulty: 'hard',
      type: 'numerical',
      topic: 'Short Forward on Yen',
      problem:
        'A trader enters a short forward contract on 100 million yen. The forward exchange rate is $0.0090 per yen. How much does the trader gain or lose if the exchange rate at end is (a) $0.0084 per yen and (b) $0.0101 per yen?',
      hints: [
        'Short forward: agreed to SELL ¥100M at $0.0090/¥',
        'Short forward gain = (K − S_T) × quantity',
      ],
      solution: {
        steps: [
          'Contract: Short ¥100,000,000 forward at K = $0.0090/¥',
          '',
          'Case (a): S_T = $0.0084/¥',
          '  Gain = (0.0090 − 0.0084) × 100,000,000 = 0.0006 × 100M',
          '  = $60,000 gain ✅',
          '',
          'Case (b): S_T = $0.0101/¥',
          '  Loss = (0.0101 − 0.0090) × 100,000,000 = 0.0011 × 100M',
          '  = $110,000 loss ❌',
        ],
        final: 'Gain = $60,000 (a) | Loss = $110,000 (b)',
      },
    },
    {
      id: 'p1_31',
      num: '1.31',
      difficulty: 'hard',
      type: 'arbitrage',
      topic: 'USD/GBP Arbitrage',
      problem:
        'USD/sterling spot and forward rates:\n• Spot: $1.2580\n• 90-day forward: $1.2556\n• 180-day forward: $1.2518\n\n(a) A 180-day European call on £1 for $1.22 costs 2 cents. Is there an arbitrage?\n(b) A 90-day European put on £1 for $1.29 costs 2 cents. Is there an arbitrage?',
      hints: [
        'For (a): 180-day forward = $1.2518. Call strike = $1.22. Compare option value to intrinsic.',
        'An in-the-money call is worth at least the discounted intrinsic value.',
        'If call price < max(F×discount − K×discount, 0), arbitrage exists.',
      ],
      solution: {
        steps: [
          'Part (a): 180-day call, K = $1.22, premium = $0.02',
          '  180-day forward = $1.2518',
          '  Call is deep in the money (F = 1.2518 >> K = 1.22)',
          '  Minimum call value ≈ (1.2518 − 1.22) × discount ≈ $0.0318 × discount',
          '  At r ≈ 5%: discount = e^(−0.05×0.5) ≈ 0.9753',
          '  Min value ≈ 0.0318 × 0.9753 = $0.0310',
          '  Call costs only $0.02 < $0.0310 → ARBITRAGE EXISTS',
          '',
          '  Strategy: Buy the call at $0.02, short the forward at $1.2518',
          '  At expiry, net gain ≥ $0.0110 per pound (risk-free)',
          '',
          'Part (b): 90-day put, K = $1.29, premium = $0.02',
          '  90-day forward = $1.2556',
          '  Put is in the money (K = 1.29 > F = 1.2556)',
          '  Min put value ≈ (1.29 − 1.2556) × discount ≈ 0.0344 × 0.9876 = $0.034',
          '  Put costs only $0.02 < $0.034 → ARBITRAGE EXISTS',
        ],
        final: 'Both (a) and (b) present arbitrage opportunities. Options are underpriced relative to their intrinsic forward value.',
      },
    },
  ],

  // ── UNSOLVED PRACTICE PROBLEMS ──
  unsolvedProblems: [
    {
      id: 'u1_1',
      num: 'U1.1',
      difficulty: 'easy',
      topic: 'Forward Payoff',
      problem:
        "An investor enters a long forward contract to buy 1,000 shares of Reliance at ₹2,400 per share in 3 months. Calculate the investor's payoff if the price at maturity is (a) ₹2,600, (b) ₹2,400, (c) ₹2,100.",
    },
    {
      id: 'u1_2',
      num: 'U1.2',
      difficulty: 'easy',
      topic: 'Call Option',
      problem:
        "An investor pays ₹15 for a call option on TCS with K = ₹3,500. The option is for 100 shares. What is the investor's profit if TCS is at (a) ₹3,650, (b) ₹3,500, (c) ₹3,400 at expiry?",
    },
    {
      id: 'u1_3',
      num: 'U1.3',
      difficulty: 'medium',
      topic: 'Put vs Short Forward',
      problem:
        "Explain the difference between (a) buying a put option on a stock with K = ₹200, premium = ₹12, and (b) entering a short forward at ₹200. When does each strategy perform better? Draw both payoff profiles for S_T ranging from ₹140 to ₹260.",
    },
    {
      id: 'u1_4',
      num: 'U1.4',
      difficulty: 'medium',
      topic: 'Hedger vs Speculator',
      problem:
        'IndiGo Airlines needs 5 million litres of jet fuel in 4 months. Current price: ₹75/litre. Futures available at ₹77/litre. (a) How would IndiGo hedge using futures? (b) If a speculator believes fuel will rise to ₹90, what position should they take? (c) Calculate each party\'s P&L if the price is actually ₹85 at maturity.',
    },
    {
      id: 'u1_5',
      num: 'U1.5',
      difficulty: 'hard',
      topic: 'Arbitrage Detection',
      problem:
        'Gold trades at ₹5,800/gram on BSE and ₹5,890/gram on MCX. Transport between exchanges costs ₹40/gram. Broker fees are ₹5/gram. (a) Does an arbitrage opportunity exist? (b) What is the maximum risk-free profit on 500 grams? (c) How will prices adjust to eliminate the arbitrage?',
    },
    {
      id: 'u1_6',
      num: 'U1.6',
      difficulty: 'hard',
      topic: 'Options Comparison',
      problem:
        "Nifty 50 is at 19,800. You have ₹2,00,000 to invest and expect a 3% rise. Compare: (A) Buy Nifty ETF units, (B) Buy Nifty call options at K = 20,000 costing ₹150/option (lot size = 50). Which gives higher returns? Which has higher risk? At what Nifty level is Strategy B superior?",
    },
  ],
}

// ── Chapter 2 Full Data ──
export const CH2_DATA = {
  id: 'ch2',
  num: 2,
  title: 'Futures Markets & Central Counterparties',

  formulas: [
    {
      id: 'initial_margin',
      category: 'Margin Accounts',
      name: 'Initial Margin Requirement',
      formula: 'Initial Margin ≈ 5% to 15% × Contract Value',
      variables: [
        { symbol: 'Contract Value', meaning: 'Futures price × Contract size' },
        { symbol: '5-15%', meaning: 'Typical range set by exchange' },
      ],
      note: 'The initial deposit required to open a futures position. Acts as performance bond.',
      example: 'Gold: 100 oz × $1,250/oz = $125,000. Initial margin = ~$6,000 (4.8%)',
    },
    {
      id: 'daily_settlement',
      category: 'Margin Accounts',
      name: 'Daily P&L Settlement',
      formula: 'Daily Gain/Loss = (F_t − F_{t-1}) × N',
      variables: [
        { symbol: 'F_t', meaning: 'Futures price today' },
        { symbol: 'F_{t-1}', meaning: 'Futures price yesterday' },
        { symbol: 'N', meaning: 'Contract size' },
      ],
      note: 'Added to or deducted from margin account daily. This is mark-to-market.',
      example: 'Gold falls $3/oz × 100 oz contract = $300 deducted from margin account',
    },
    {
      id: 'margin_call',
      category: 'Margin Accounts',
      name: 'Margin Call Trigger',
      formula: 'Margin Call if Balance < Maintenance Margin',
      variables: [
        { symbol: 'Balance', meaning: 'Current margin account balance' },
        { symbol: 'Maintenance Margin', meaning: 'Minimum balance (~75% of initial)' },
      ],
      note: 'When triggered, must top up to INITIAL margin (not just maintenance).',
      example: 'Initial = $6,000, Maintenance = $4,500. If balance drops to $4,200 → call to add $1,800',
    },
    {
      id: 'convergence',
      category: 'Pricing',
      name: 'Convergence at Maturity',
      formula: 'As T → 0: F_T → S_T',
      variables: [
        { symbol: 'F_T', meaning: 'Futures price at expiry' },
        { symbol: 'S_T', meaning: 'Spot price at expiry' },
      ],
      note: 'Arbitrage ensures futures price equals spot at delivery. Self-correcting mechanism.',
      example: 'If F_T > S_T: buy spot, deliver via futures → profit until prices equalize',
    },
    {
      id: 'open_interest',
      category: 'Market Data',
      name: 'Open Interest',
      formula: 'OI increases when NEW long + NEW short enter',
      variables: [
        { symbol: 'OI', meaning: 'Total outstanding contracts (open positions)' },
      ],
      note: 'OI increases when both sides are new. Decreases when positions are closed. Unchanged when old position transferred.',
      example: 'OI = 1,000. A new buyer and new seller transact → OI = 1,001',
    },
  ],

  summary: {
    tagline: 'How futures markets actually work: margins, clearing, and convergence.',
    keyPoints: [
      {
        icon: '💰',
        title: 'Margin Mechanics',
        body: 'Initial margin (~5-15%) opens position. Mark-to-market daily settles P&L. If balance falls below maintenance margin → margin call (must top up to initial). This prevents accumulation of large losses.',
      },
      {
        icon: '🏦',
        title: 'Central Counterparties (CCPs)',
        body: 'CCPs insert themselves as buyer to every seller and seller to every buyer. Virtually eliminate counterparty risk. Post-2008: Dodd-Frank and EMIR mandated CCPs for standardized OTC derivatives. Major CCPs: CME, LCH, ICE.',
      },
      {
        icon: '🎯',
        title: 'Convergence Principle',
        body: 'Futures prices MUST equal spot at expiry (arbitrage enforces this). If F > S: buy spot, short futures → profit. If F < S: short spot, buy futures → profit. This price pressure forces convergence.',
      },
      {
        icon: '📋',
        title: 'Contract Specification',
        body: 'Every detail standardized by exchange: underlying asset quality, contract size, delivery month, location, price quote units, minimum tick size. Standardization creates liquidity — everyone trades identical instruments.',
      },
      {
        icon: '⚖️',
        title: 'Forward vs Futures (Key Differences)',
        body: 'Futures: standardized, exchange, daily MTM, CCP, margin required, liquid. Forwards: OTC, customized, settled at maturity, counterparty risk, no upfront cost, illiquid. Price difference exists due to daily settlement interest rate effect.',
      },
      {
        icon: '🔄',
        title: 'Post-2008 OTC Reform',
        body: 'Dodd-Frank (US) and EMIR (EU) transformed OTC markets: mandatory CCP clearing for standard products, trade repositories for all OTC trades, bilateral margin requirements. Made markets safer but more expensive.',
      },
    ],
    mustRemember: [
      'Daily MTM gain/loss = (F_today − F_yesterday) × contract size',
      'Margin call triggers when balance < maintenance margin',
      'Top up to INITIAL margin (not maintenance) after call',
      'Futures price converges to spot at maturity (arbitrage enforces)',
      'Open interest increases only when BOTH sides are new to market',
      'Physical delivery is rare — most futures closed before expiry',
      'CCP = buyer to every seller, seller to every buyer',
    ],
    connections: [
      "Margin mechanics directly connect to Chapter 3's hedging cost analysis",
      "Convergence principle is the foundation of Chapter 5's forward pricing models",
      'CCP concepts expanded in Chapter 9 (XVAs) and Chapter 24 (credit risk)',
    ],
  },

  examples: [
    {
      id: 'ex2_1',
      num: '2.1',
      type: 'worked',
      title: "Hull's Gold Futures Margin Example",
      scenario: 'Mark-to-Market Over 11 Days',
      problem:
        'An investor takes a long position in 2 gold futures contracts (100 oz each) at $1,250/oz. Initial margin = $6,000/contract ($12,000 total). Maintenance margin = $4,500/contract ($9,000 total). Track the margin account over 11 days given these daily prices: 1246.10, 1248.30, 1241.00, 1244.60, 1241.30, 1240.10, 1236.20, 1229.90, 1230.80, 1225.40, 1228.10',
      solution: [
        'Contract: 2 × 100 oz = 200 oz exposure',
        'Initial balance: $12,000',
        '',
        'Day 1: $1,250 → $1,246.10 (−$3.90/oz)',
        '  Daily loss: 200 × $3.90 = $780. Balance: $11,220',
        'Day 2: $1,248.30 (+$2.20/oz)',
        '  Daily gain: 200 × $2.20 = $440. Balance: $11,660',
        'Day 3: $1,241.00 (−$7.30/oz)',
        '  Daily loss: 200 × $7.30 = $1,460. Balance: $10,200',
        'Day 4: $1,244.60 (+$3.60)',
        '  Balance: $10,920',
        'Day 5: $1,241.30 (−$3.30)',
        '  Balance: $10,260',
        'Day 6: $1,240.10 (−$1.20)',
        '  Balance: $10,020',
        'Day 7: $1,236.20 (−$3.90)',
        '  Balance: $9,240',
        'Day 8: $1,229.90 (−$6.30)',
        '  Balance: $8,000. Note: $8,000 < $9,000 (maintenance) → MARGIN CALL',
        '  Must top up to $12,000 → deposit $4,000',
        'Day 9: $1,230.80 (+$0.90)',
        '  Balance: $13,080',
        'Day 10: $1,225.40 (−$5.40)',
        '  Balance: $11,000',
        'Day 11: $1,228.10 (+$2.70)',
        '  Balance: $11,540',
        '',
        'Cumulative loss over 11 days: $1,250 − $1,228.10 = $21.90/oz × 200 = $4,380',
        'Plus deposits: Total cost = initial $12,000 + $4,000 top-up = $16,000',
      ],
      insight:
        'This is Hull\'s Table 2.1 example. Notice the margin call on Day 8 — the investor must immediately deposit more funds or their position is liquidated. This daily settlement is what makes futures safe for the exchange.',
      tags: ['Margin', 'Mark-to-Market', 'Gold Futures'],
    },
    {
      id: 'ex2_2',
      num: '2.2',
      type: 'worked',
      title: 'CCP Margin Netting Example',
      scenario: 'How CCPs Reduce Total System Collateral',
      problem:
        'Five banks (A–E) have the following bilateral OTC positions (in $B): A→B: +10, A→C: −5, B→C: +3, C→D: +8, D→E: −6. Without CCP, each bilateral position requires collateral. Show how CCP netting reduces total collateral required.',
      solution: [
        'Without CCP (bilateral):',
        '  Each gross bilateral position requires margin',
        '  Total gross exposure: 10+5+3+8+6 = $32B',
        '  Each counterparty pair must post margin separately',
        '',
        'With CCP (multilateral netting):',
        '  CCP calculates net position for each bank:',
        '  A: +10 − 5 = +$5B net',
        '  B: −10 + 3 = −$7B net',
        '  C: +5 − 3 + 8 = +$10B net',
        '  D: −8 − 6 = −$14B net',
        '  E: +6 = +$6B net',
        '',
        '  Total margin required: only on NET positions',
        '  Net total = |5|+|7|+|10|+|14|+|6| = $42B',
        '  But with netting, opposite positions cancel → significant reduction',
        '',
        'Key benefit: eliminates "wrong-way" risk and cascading defaults',
      ],
      insight:
        'CCPs reduce total collateral in the system via multilateral netting. More importantly, they prevent a default by one party from cascading to all counterparties.',
      tags: ['CCP', 'Netting', 'Collateral'],
    },
  ],

  problems: [
    {
      id: 'p2_11',
      num: '2.11',
      difficulty: 'medium',
      type: 'numerical',
      topic: 'Margin Call Calculation',
      problem:
        'Suppose you enter into a short futures contract to sell July silver for $17.20 per ounce. The size of the contract is 5,000 ounces. The initial margin is $4,000, and the maintenance margin is $3,000. What change in the futures price will lead to a margin call? What happens if you do not meet the margin call?',
      hints: [
        'Short futures: you profit when price falls',
        'Margin call when balance drops below $3,000',
        'You start with $4,000; can lose $1,000 before margin call',
        'Loss on short = (new price − entry price) × 5,000',
      ],
      solution: {
        steps: [
          'You are SHORT silver at $17.20/oz',
          'Initial margin: $4,000 | Maintenance: $3,000',
          'Threshold loss before margin call: $4,000 − $3,000 = $1,000',
          '',
          'Short position loses when price RISES',
          'Loss = (F_new − 17.20) × 5,000 = $1,000',
          'F_new − 17.20 = 1,000 / 5,000 = $0.20',
          'F_new = $17.40/oz',
          '',
          'Margin call triggered if silver rises to $17.40 or above',
          '',
          'If you do NOT meet the margin call:',
          '  Broker closes your position immediately',
          '  Any remaining margin is returned (minus losses)',
          '  You lose the difference between your margin and losses',
        ],
        final: 'Margin call when silver price rises to $17.40/oz (increase of $0.20)',
      },
    },
    {
      id: 'p2_12',
      num: '2.12',
      difficulty: 'hard',
      type: 'numerical',
      topic: 'Hedger vs Speculator Tax',
      problem:
        'In September 2021, a company takes a long position on May 2022 crude oil futures at $48.30/barrel. It closes out in March 2022 at $50.50. Settlement price Dec 31, 2021 = $49.10. Contract = 1,000 barrels. What is the company\'s total profit? How is it taxed if (a) hedger and (b) speculator with Dec 31 year-end?',
      hints: [
        'Total profit = (closing price − opening price) × contract size',
        'Hedger: full profit recognized when hedge completed (March)',
        'Speculator: Dec 31 settlement creates year-end mark (60/40 rule in US)',
      ],
      solution: {
        steps: [
          'Entry: Sept 2021 at $48.30',
          'Dec 31 settlement: $49.10 (unrealized gain = $0.80/bbl)',
          'Closing: March 2022 at $50.50',
          '',
          'Total profit = ($50.50 − $48.30) × 1,000 = $2,200',
          '',
          'Case (a) Hedger:',
          '  Full $2,200 recognized in March 2022 (when hedge settled)',
          '  Taxed as ordinary income in 2022 tax year',
          '',
          'Case (b) Speculator (US 60/40 rule):',
          '  Year-end mark: ($49.10 − $48.30) × 1,000 = $800 gain in 2021',
          '  2021 tax: 60% × $800 = $480 long-term gain; 40% × $800 = $320 short-term',
          '',
          '  2022 remaining: ($50.50 − $49.10) × 1,000 = $1,400 gain',
          '  2022 tax: 60% × $1,400 = $840 long-term; 40% × $1,400 = $560 short-term',
        ],
        final: 'Total profit = $2,200. Hedger pays in 2022. Speculator splits: $800 in 2021, $1,400 in 2022 (both under 60/40 rule).',
      },
    },
    {
      id: 'p2_17',
      num: '2.17',
      difficulty: 'medium',
      type: 'numerical',
      topic: 'Orange Juice Futures Margin',
      problem:
        'A trader buys two July frozen orange juice concentrate futures contracts (15,000 lbs each). Futures price = 160 cents/lb. Initial margin = $6,000/contract. Maintenance margin = $4,500/contract. What price change leads to a margin call? Under what circumstances could $2,000 be withdrawn from the margin account?',
      hints: [
        'Total initial margin = 2 × $6,000 = $12,000',
        'Total maintenance = 2 × $4,500 = $9,000',
        'Loss tolerance = $12,000 − $9,000 = $3,000',
        'Loss on LONG = (entry − new price) × total quantity',
      ],
      solution: {
        steps: [
          'Long position: 2 contracts × 15,000 lbs = 30,000 lbs',
          'Entry price: 160 cents = $1.60/lb',
          'Total initial margin: $12,000 | Maintenance: $9,000',
          '',
          'Margin call when loss exceeds $12,000 − $9,000 = $3,000',
          'For LONG: loss = (1.60 − new price) × 30,000 = $3,000',
          'New price = 1.60 − (3,000/30,000) = 1.60 − 0.10 = $1.50/lb = 150 cents/lb',
          '',
          'Margin call triggered if OJ price falls to 150 cents/lb',
          '',
          'Withdrawal of $2,000:',
          '  Current balance must exceed initial margin by at least $2,000',
          '  Balance ≥ $12,000 + $2,000 = $14,000',
          '  Need cumulative gain = $14,000 − $12,000 = $2,000',
          '  Gain = (new price − 1.60) × 30,000 = $2,000',
          '  New price = 1.60 + (2,000/30,000) = $1.6667/lb ≈ 166.67 cents',
          '',
          'Can withdraw $2,000 if OJ price rises to 166.67 cents/lb',
        ],
        final: 'Margin call at 150 cents/lb (−10 cents). Withdrawal possible above 166.67 cents/lb (+6.67 cents).',
      },
    },
    {
      id: 'p2_21',
      num: '2.21',
      difficulty: 'hard',
      type: 'numerical',
      topic: 'Clearing House Margin',
      problem:
        'A clearing house member is long 100 contracts (settlement price = $50,000/contract). Original margin = $2,000/contract. The next day, member becomes responsible for 20 additional long contracts at $51,000, and settlement price ends at $50,200. How much must be added to margin account?',
      hints: [
        'Start: 100 contracts × $50,000',
        "Add: 20 contracts × $51,000 (member's new responsibility)",
        'End: all 120 positions at $50,200',
        'Net change = gains from price move minus any losses from new positions',
      ],
      solution: {
        steps: [
          'Step 1: Initial position',
          '  100 long contracts at $50,000 settlement',
          '  Original margin: 100 × $2,000 = $200,000',
          '',
          'Step 2: Next day events',
          '  Add 20 contracts at $51,000 (new commitment)',
          '  New settlement price: $50,200',
          '',
          'Step 3: Gain/loss on original 100 contracts',
          '  Daily gain = ($50,200 − $50,000) × 100 = $20,000',
          '',
          'Step 4: Loss on 20 new contracts',
          '  New contracts at $51,000, now worth $50,200',
          '  Loss = ($51,000 − $50,200) × 20 = $16,000',
          '',
          'Step 5: New margin requirement',
          '  New total: 120 contracts × $2,000 = $240,000',
          '  Previous: $200,000',
          '  New margin needed: $240,000 − $200,000 = $40,000',
          '',
          'Step 6: Net cash flow',
          '  Gains: +$20,000',
          '  Losses: −$16,000',
          '  Extra margin: −$40,000',
          '  Must ADD: −$20,000 + $16,000 + $40,000 = $36,000',
        ],
        final: 'Must add $36,000 to margin account with clearing house.',
      },
    },
  ],

  unsolvedProblems: [
    {
      id: 'u2_1',
      num: 'U2.1',
      difficulty: 'easy',
      topic: 'Margin Call Trigger',
      problem:
        'You enter a long Nifty futures contract at 20,000. Contract size = 50. Initial margin = ₹1,00,000. Maintenance margin = ₹75,000. (a) What daily Nifty price drop triggers a margin call? (b) How much must you deposit? (c) If Nifty rises 200 points, how much can you withdraw?',
    },
    {
      id: 'u2_2',
      num: 'U2.2',
      difficulty: 'medium',
      topic: 'Convergence Arbitrage',
      problem:
        'Gold spot = ₹5,900/gram. Gold 3-month futures = ₹6,100/gram. Storage cost = ₹20/gram for 3 months. Financing cost = 1.5% over 3 months. (a) What is the theoretical futures price? (b) Is there an arbitrage opportunity? (c) How would you execute it?',
    },
    {
      id: 'u2_3',
      num: 'U2.3',
      difficulty: 'medium',
      topic: 'Open Interest',
      problem:
        "At market open, Nifty December futures open interest = 5,000. During the day: (a) Trader A (new) buys 100 from Trader B (new). (b) Trader C (holds long 200) sells 200 to Trader D (new). (c) Trader E (holds long 100) closes with Trader F (holds short 100). What is OI at end of day?",
    },
    {
      id: 'u2_4',
      num: 'U2.4',
      difficulty: 'hard',
      topic: 'Forward vs Futures Profit',
      problem:
        'Sterling exchange rate: 90-day forward = $1.2000; 90-day futures = $1.2000. Trader A is long £1M sterling forward. Trader B is long 16 futures contracts (£62,500 each). If sterling moves to $1.2500 in 30 days and stays there for the remaining 60 days, compare the total dollar gains for A and B. Why might they differ? (Assume 5% interest rate.)',
    },
    {
      id: 'u2_5',
      num: 'U2.5',
      difficulty: 'hard',
      topic: 'CCP Benefits',
      problem:
        "Four banks have bilateral OTC interest rate swap exposures (in $B): A↔B: +15, A↔C: -8, B↔C: +12, C↔D: -10, B↔D: +6. (a) Calculate each bank's gross bilateral exposure. (b) If all trades cleared through a CCP, what is each bank's net position? (c) By what % is total collateral reduced?",
    },
  ],
}

// ── Chapter data map ──
export const CHAPTER_DATA = {
  ch1: CH1_DATA,
  ch2: CH2_DATA,
}

// ── XP & Level System ──
export const LEVEL_NAMES = [
  'Intern', 'Analyst', 'Associate', 'VP', 'Director', 'MD', 'Partner', 'Legend',
]

export const ACHIEVEMENTS = [
  { id: 'first_concept', icon: '🌱', name: 'First Steps', desc: 'Read your first concept' },
  { id: 'ch1_complete', icon: '📗', name: 'Ch.1 Master', desc: 'Completed all Ch.1 concepts' },
  { id: 'ch2_complete', icon: '📘', name: 'Ch.2 Master', desc: 'Completed all Ch.2 concepts' },
  { id: 'first_trade', icon: '💼', name: 'Trader Initiate', desc: 'Executed first trade' },
  { id: 'first_win', icon: '💰', name: 'First Profit', desc: 'Made profit on a trade' },
  { id: 'quiz_ace_1', icon: '🎯', name: 'Quiz Ace Ch.1', desc: 'Scored 8+ on Ch.1 quiz' },
  { id: 'quiz_ace_2', icon: '🏹', name: 'Quiz Ace Ch.2', desc: 'Scored 8+ on Ch.2 quiz' },
  { id: 'fc_master', icon: '🃏', name: 'Card Shark', desc: 'Mastered 10+ flashcards' },
  { id: 'speed_done', icon: '⚡', name: 'Speed Reader', desc: 'Completed speed learn' },
  { id: 'arbitrageur', icon: '🔄', name: 'Arbitrageur', desc: 'Exploited a price gap' },
  { id: 'margin_master', icon: '💹', name: 'Margin Master', desc: 'Survived a margin call' },
  { id: 'level5', icon: '⭐', name: 'Level 5', desc: 'Reached Level 5' },
  { id: 'problem_solver', icon: '🔢', name: 'Problem Solver', desc: 'Solved 5 textbook problems' },
  { id: 'formula_master', icon: '📐', name: 'Formula Master', desc: 'Viewed all formulas in a chapter' },
]
